spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/springboot
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
      show-sql: true
      format-sql: true
      type: info
      use-sql-comments: true
      properties:
        hibernate.use_sql_comments: true
        hibernate.format_sql: true

springdoc:
  show-actuator: true
  paths-to-match: /**
  packages-to-scan: com.FPTU

management:
  endpoint:
    health:
      show-details: ALWAYS
    endpoints:
      web:
        exposure:
          include: "*"

jwt:
  secretKey: secret
  issuer: www.fptu.com
  expirationMinute: 10

swagger:
  contact-name: Kong
  contact-mail: congnttse172288@fpt.edu.vn
  contact-url: https://www.facebook.com/profile.php?id=100008273866423
  app-name: DrawingCourseWeb
  app-description: "This is a DrawingCourseWeb. This project includes : Spring Boot(2.7.4), Spring Data JPA, Spring Validation, Spring Security + JWT Token, MySQL, Mapstruct, Lombok, Swagger"
  app-version: 2.0.0
  app-license-url: https://www.apache.org/licenses/LICENSE-2.0.html
  app-license: Apache 2.0
